### ISSUE TITLE
ABY (or ABY2.0) in MOTION?

### ISSUE THREAD

**Issue by byzhang** [encryptogroup/MOTION#1]
The MOTION has a better modular design. Would you try to port ABY (or even ABY2.0) in MOTION? When an application only needs 2PC, ABY2.0 is still faster.

**Comment by Oleksandr-Tkachenko** [comment]
We plan to add more optimized two-party protocols in a few months.

**Comment by Oleksandr-Tkachenko** [comment]
See https://github.com/encryptogroup/MOTION2NX.
