### ISSUE TITLE
How do you convert a publicly known constant value into a share?

### ISSUE THREAD

**Issue by benjaminrsherman** [encryptogroup/MOTION#11]
If there's a value which is publicly known by all parties (e.g. a loop counter), is it possible to convert this into a Share without using `Party::In()` to provide the value as input from a specific party?

**Comment by Oleksandr-Tkachenko** [comment]
It is possible for arithmetic constants via `Party::In<...kArithmeticConstant>(...)`. No boolean constants yet unfortunately.
