### ISSUE TITLE
Compilation with the intel version of the Macbook pro failed with the following message：No rule to make target `extern/boost/lib/libboost_fiber.a', needed by `bin/crosstabs'.  Stop.

### ISSUE THREAD

**Issue by Cryptographer63** [encryptogroup/MOTION#17]
Compilation with the intel version of the Macbook pro failed with the following message

[ 92%] Linking CXX static library ../../lib/libmotion.a
[ 92%] Built target motion
[ 92%] Building CXX object src/examples/tutorial/crosstabs/CMakeFiles/crosstabs.dir/crosstabs_main.cpp.o
[ 93%] Building CXX object src/examples/tutorial/crosstabs/CMakeFiles/crosstabs.dir/common/crosstabs.cpp.o
make[2]: *** No rule to make target `extern/boost/lib/libboost_fiber.a', needed by `bin/crosstabs'.  Stop.
make[1]: *** [src/examples/tutorial/crosstabs/CMakeFiles/crosstabs.dir/all] Error 2
make: *** [all] Error 2

**Comment by Oleksandr-Tkachenko** [comment]
Can you tell us more about your setup: compiler version, Boost already installed in the system? Please also give us the full build log.
