### ISSUE TITLE
How to implement more protocols

### ISSUE THREAD

**Issue by Cryptographer63** [encryptogroup/MOTION#18]
I want to implement some protocols based on replication secret sharing on top of Motion, such as aby3,falcon etc. I don't know if this idea is feasible, if so, can you briefly explain the idea.

**Comment by Oleksandr-Tkachenko** [comment]
The bare minimum you would need is creating `Wire` and `Gate` objects for your protocols. The communication is realized using flatbuffers (look for .fbs files as an example) and how the logic in some of the `Gate`s works, e.g., [GMW XOR gate](https://github.com/encryptogroup/MOTION/blob/16fe358393912f18b91a0606be7f5e9450f75869/src/motioncore/protocols/boolean_gmw/boolean_gmw_gate.cpp#L365). The messages are sent between parties via `CommunicationLayer` objects that you can use to communicate between parties pairwise. You would also need to create "communication channels" for moving the received information to the right place, which can be done using [special future/promise pairs](https://github.com/encryptogroup/MOTION/blob/master/src/motioncore/utility/reusable_future.h), which are waitable objects with support for fibers (i.e., they don't block the thread). You don't need to touch other protocols and primitives for adding new functionality or even mixing it with the existing protocols. The logic for executing `Gate`s can be found [here](https://github.com/encryptogroup/MOTION/blob/master/src/motioncore/executor/gate_executor.cpp).

I will try to find some time to describe this in more detail.

**Comment by Cryptographer63** [comment]
Thank you very much! 
I have read the source code carefully and already have a rough idea of the process. However, I was thinking of implementing a replication secret sharing based protocol like ABY3, Falcon, etc. on top of Motion, but I haven't figured out how to do it yet. For example, in which class should I define the secret share pair...

**Comment by Cryptographer63** [comment]
> The bare minimum you would need is creating `Wire` and `Gate` objects for your protocols. The communication is realized using flatbuffers (look for .fbs files as an example) and how the logic in some of the `Gate`s works, e.g., [GMW XOR gate](https://github.com/encryptogroup/MOTION/blob/16fe358393912f18b91a0606be7f5e9450f75869/src/motioncore/protocols/boolean_gmw/boolean_gmw_gate.cpp#L365). The messages are sent between parties via `CommunicationLayer` objects that you can use to communicate between parties pairwise. You would also need to create "communication channels" for moving the received information to the right place, which can be done using [special future/promise pairs](https://github.com/encryptogroup/MOTION/blob/master/src/motioncore/utility/reusable_future.h), which are waitable objects with support for fibers (i.e., they don't block the thread). You don't need to touch other protocols and primitives for adding new functionality or even mixing it with the existing protocols. The logic for executing `Gate`s can be found [here](https://github.com/encryptogroup/MOTION/blob/master/src/motioncore/executor/gate_executor.cpp).
> 
> I will try to find some time to describe this in more detail.

Thank you very much! 
I have read the source code carefully and already have a rough idea of the process. However, I was thinking of implementing a replication secret sharing based protocol like ABY3, Falcon, etc. on top of Motion, but I haven't figured out how to do it yet. For example, in which class should I define the secret share pair...

**Comment by Oleksandr-Tkachenko** [comment]
All the information about the secret-shared values is stored in `Wire` objects - take a look at arithmetic GMW `Wire` as an example. The `Share` class is used only as a higher-level interface to basically abstract away the protocol details, e.g., to have the same API for integer operations for both arithmetic and boolean circuits.

The "sharing" of non-constant input values should be performed via `Gate`s. [Here](https://github.com/encryptogroup/MOTION/blob/6a7c1c759d2269127df9d2cc799a2c3448310b58/src/motioncore/protocols/arithmetic_gmw/arithmetic_gmw_gate.cpp#L88) is an example.
