### ISSUE TITLE
Does MOTION support big number operations?

### ISSUE THREAD

**Issue by bonomigo** [encryptogroup/MOTION#44]
MOTION supports 64-bit operations with uint64 and int64_t, but it doesn't seem to support integer operations over 64 bits, such as big integer operations. I'm wondering if it's correct that it doesn't support them.

**Comment by robinhundt** [comment]
Hi, as far as I'm aware MOTION unfortunately does not support big number operations.

**Comment by bonomigo** [comment]
Hi robinhundt, thanks for your reply. I took a look at the MOTION code and realized that it doesn't support big number operations.
