### ISSUE TITLE
Retrieving incorrect outputs

### ISSUE THREAD

**Issue by maDnemo** [encryptogroup/MOTION#5]
I was trying to view the results of operations in the benchmark and benchmark_integers examples using the As() and Or() functions, but I get incorrect results for all of the operations. I was wondering if there is an issue with the operations, or if I am not obtaining the results correctly?

**Comment by Oleksandr-Tkachenko** [comment]
What output do you expect from those operations? I think there we constructed just dummy wires to eliminate any possible effects of input sharing.

The [millionaires' example](https://github.com/encryptogroup/MOTION/blob/454ee6c5f22810285e4903d1667bc0fa7d5184a6/src/examples/millionaires_problem/common/millionaire.cpp#L40) might actually be a better starting point to get familiar with MOTION (if that was your goal). Also, three more examples will be added in a few days.

**Comment by maDnemo** [comment]
I modified the DummyArithmeticGmwShare function such that dummy_input has value 2, and verified with As() that the share has value 2. I then tried adding them together with the + operation and used Out() on the result. When I tried to use As() after that, the result I got was 8, not 4. In addition, I modified DummyBooleanGmwShare so that I could set the entire BitVector to true or false, but no matter what values I used, I always got the same outputs for And, Or, Xor, and Inv.

**Comment by Oleksandr-Tkachenko** [comment]
If I understand you correctly, you have two parties in MPC, who both create two additively shared wires with the "local" value 2, so what is shared is 2 + 2 = 4. Now, you add them together and have 4 in the wire of one party and the same in the wire of another party. Afterwards, you put an output gate (`Out()`) on the result and both parties retrieve the cleartext value, which equals 4 + 4 = 8. Could you please check if this is the case?

**Comment by maDnemo** [comment]
It appears that this is the case. How should I create one share for each party and add their values together? Is that done with In()?

**Comment by Oleksandr-Tkachenko** [comment]
yes, it might be helpful to also take a look at the previously linked millionaires' example

**Comment by maDnemo** [comment]
That helped me understand how the shares work, thank you!
